final Map<String, List<String>> themes = {
  "Squid Game": [
    "assets/squidgame/GongYoo.jpeg",
    "assets/squidgame/FrontMan.jpeg",
    "assets/squidgame/Player001.jpeg",
    "assets/squidgame/Player196.jpeg",
    "assets/squidgame/Player222.jpeg",
    "assets/squidgame/Player333.jpeg",
    "assets/squidgame/Player388.jpeg",
    "assets/squidgame/Player456.jpeg",
    "assets/squidgame/SquidGame.jpeg",
    "assets/squidgame/SquidGuards.jpeg",
    "assets/squidgame/Thanos.jpeg",
    "assets/squidgame/Salesman.jpg",
  ],
  "Alice In Borderland": [
    "assets/aliceinborderland/img1.png",
    "assets/aliceinborderland/img2.png",
    "assets/aliceinborderland/img3.png",
    "assets/aliceinborderland/img4.png",
    "assets/aliceinborderland/img5.png",
    "assets/aliceinborderland/img6.png",
    "assets/aliceinborderland/img7.png",
    "assets/aliceinborderland/img8.png",
    "assets/aliceinborderland/img9.png",
    "assets/aliceinborderland/img10.png",
    "assets/aliceinborderland/img11.png",
    "assets/aliceinborderland/img12.png",
  ],
  "Stranger Things": [
    "assets/strangerthings/img1.png",
    "assets/strangerthings/img2.png",
    "assets/strangerthings/img3.png",
    "assets/strangerthings/img4.png",
    "assets/strangerthings/img5.png",
    "assets/strangerthings/img6.png",
    "assets/strangerthings/img7.png",
    "assets/strangerthings/img8.png",
    "assets/strangerthings/img9.png",
    "assets/strangerthings/img10.png",
    "assets/strangerthings/img11.png",
    "assets/strangerthings/img12.png",
  ],


  "Billy and Mandy": [
    "assets/billyandmandy/img1.png",
    "assets/billyandmandy/img2.png",
    "assets/billyandmandy/img3.png",
    "assets/billyandmandy/img4.png",
    "assets/billyandmandy/img5.png",
    "assets/billyandmandy/img6.png",
    "assets/billyandmandy/img7.png",
    "assets/billyandmandy/img8.png",
    "assets/billyandmandy/img9.png",
    "assets/billyandmandy/img10.png",
    "assets/billyandmandy/img11.png",
    "assets/billyandmandy/img12.png",
  ],
  "Minecraft": [
    "assets/minecraft/img1.png",
    "assets/minecraft/img2.png",
    "assets/minecraft/img3.png",
    "assets/minecraft/img4.png",
    "assets/minecraft/img5.png",
    "assets/minecraft/img6.png",
    "assets/minecraft/img7.png",
    "assets/minecraft/img8.png",
    "assets/minecraft/img9.png",
    "assets/minecraft/img10.png",
    "assets/minecraft/img11.png",
    "assets/minecraft/img12.png",
  ],
  "Oggy And The Cockroaches": [
    "assets/oggyandthecockroaches/img1.png",
    "assets/oggyandthecockroaches/img2.png",
    "assets/oggyandthecockroaches/img3.png",
    "assets/oggyandthecockroaches/img4.png",
    "assets/oggyandthecockroaches/img5.png",
    "assets/oggyandthecockroaches/img6.png",
    "assets/oggyandthecockroaches/img7.png",
    "assets/oggyandthecockroaches/img8.png",
    "assets/oggyandthecockroaches/img9.png",
    "assets/oggyandthecockroaches/img10.png",
    "assets/oggyandthecockroaches/img11.png",
    "assets/oggyandthecockroaches/img12.png",
  ],
  "From": [
    "assets/from/img1.png",
    "assets/from/img2.png",
    "assets/from/img3.png",
    "assets/from/img4.png",
    "assets/from/img5.png",
    "assets/from/img6.png",
    "assets/from/img7.png",
    "assets/from/img8.png",
    "assets/from/img9.png",
    "assets/from/img10.png",
    "assets/from/img11.png",
    "assets/from/img12.png",
  ],
};
